# Generated by Django 4.2.19 on 2025-02-14 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('returned_time', models.DateTimeField(db_index=True, default=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='book.book')),
                ('book_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='book.detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='user.user')),
            ],
        ),
    ]
