# Generated by Django 4.2.19 on 2025-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='returned_time',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
