# Generated by Django 4.2.19 on 2025-02-14 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('publish_time', models.CharField(max_length=100)),
                ('publishing_house', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=16)),
                ('count', models.IntegerField(default=1)),
                ('serial', models.CharField(max_length=32, unique=True)),
                ('desc', models.TextField(default='')),
                ('is_disabled', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('is_disabled', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='book.book')),
            ],
        ),
    ]
